### PR TITLE
Change Localestring

### LINKED ISSUE #2: :bug: comma placement
12,03,143

should be

1,203,143

### PR DESCRIPTION
**Pull request by billthebuilder**
Fixes #2

### CODE REVIEW

**Review by StanleyMasinde — CHANGES_REQUESTED** [review]
Please use en-us or en-uk
I had also suggested the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) interface

**Comment by cyrus43** [comment]
But en-ke works too.. maybe we try en-Uk juu en-Us inakataa

**Comment by billthebuilder** [comment]
> But en-ke works too.. maybe we try en-Uk juu en-Us inakataa
hata en-us inafanya pia

**Comment by StanleyMasinde** [comment]
> But en-ke works too.. maybe we try en-Uk juu en-Us inakataa

Great

**Pull request merged**
